//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alfursan.Web.Views.Home.App_LocalResources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your &lt;b&gt;Account files &lt;/b&gt;are here!&lt;br/&gt;
        ///Please click  &lt;a href=&quot;/Archive/Files/2&quot;&gt;Go to Accounts&lt;/a&gt; button and view your account files..
        /// </summary>
        public static string AccountDesc {
            get {
                return ResourceManager.GetString("AccountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Accounts.
        /// </summary>
        public static string BtnAccountDocs {
            get {
                return ResourceManager.GetString("BtnAccountDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string BtnOther {
            get {
                return ResourceManager.GetString("BtnOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string BtnSend {
            get {
                return ResourceManager.GetString("BtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Shipments.
        /// </summary>
        public static string BtnShipmmentDocs {
            get {
                return ResourceManager.GetString("BtnShipmmentDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string BtnUpload {
            get {
                return ResourceManager.GetString("BtnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Document.
        /// </summary>
        public static string FileTypeAccountDoc {
            get {
                return ResourceManager.GetString("FileTypeAccountDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string FileTypeOther {
            get {
                return ResourceManager.GetString("FileTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Document.
        /// </summary>
        public static string FileTypeShipmentDoc {
            get {
                return ResourceManager.GetString("FileTypeShipmentDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your other documents are here as your order invoices.&lt;br/&gt;
        ///Please click  &lt;a href=&quot;/Archive/Files/3&quot;&gt;Others&lt;/a&gt; button and view your any other kind of various files..
        /// </summary>
        public static string OtherDesc {
            get {
                return ResourceManager.GetString("OtherDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send bulk e-mails to the saved users on the system..
        /// </summary>
        public static string SendEmailText {
            get {
                return ResourceManager.GetString("SendEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send E-mail.
        /// </summary>
        public static string SendEmailTitle {
            get {
                return ResourceManager.GetString("SendEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your &lt;b&gt; Shipments Documents &lt;/b&gt;are here&lt;br/&gt;
        ///Invoice, Packing List, Eur1, AWB and more.&lt;br/&gt;
        ///Please click  &lt;a href=&quot;/Archive/Files/1&quot;&gt;Go to Shipments&lt;/a&gt; button and view your shipment files..
        /// </summary>
        public static string ShipmentDocDesc {
            get {
                return ResourceManager.GetString("ShipmentDocDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfursan File Management.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload various files into your account..
        /// </summary>
        public static string UploadText {
            get {
                return ResourceManager.GetString("UploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading the shipment files, account files and other files into the related user’s account.
        ///Before upload a file please select the related user and file destination. &lt;br/&gt;
        ///PLEASE MAKE SURE THAT YOU’VE UPLOADED THE RIGHT FILE TO THE RIGHT USER..
        /// </summary>
        public static string UploadTextAdmin {
            get {
                return ResourceManager.GetString("UploadTextAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string UploadTitle {
            get {
                return ResourceManager.GetString("UploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ALFURSAN&apos;s online archive system.&lt;br/&gt;
        ///        This system has been created just for our customers.&lt;br /&gt;
        ///        By this system, our customers can follow up their business runing.&lt;br /&gt;
        ///        You can upload shipment documents, account statements and any kind of various documents into related clients’ user accounts by using the system.&lt;br/&gt;
        ///        Operate clear!.
        /// </summary>
        public static string WelcomeTextAdmin {
            get {
                return ResourceManager.GetString("WelcomeTextAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Customer,&lt;br/&gt;&lt;br/&gt;
        ///Welcome to ALFURSAN&apos;s online archive system.&lt;br/&gt;
        ///We’ve created this system just for our Alfursan’s customers business follow up.&lt;br/&gt;&lt;br/&gt;
        ///You can view your shipment documents, account statements, various documents and all the history of your business runing.&lt;br/&gt;
        ///Please click the buttons below and view your files.&lt;br/&gt;
        ///If you need any asistance, please don’t hesitate to contact us.&lt;br/&gt;
        ///&lt;br/&gt;Best Regards,.
        /// </summary>
        public static string WelcomeTextCustomer {
            get {
                return ResourceManager.GetString("WelcomeTextCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALFURSAN&apos;s Client Login.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
