//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alfursan.Web.App_GlobalResources.MailMessage", typeof(MailMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Dear &lt;Name&gt; &lt;Surname&gt; ,&lt;/h4&gt;
        ///&lt;p&gt;Your password has been changed on ALFURSAN’s Client Login System.&lt;/p&gt;
        ///&lt;p&gt;
        ///Your e-mail address : &lt;Email&gt;&lt;br/&gt;
        ///
        ///Your new password is : &lt;Password&gt;&lt;/p&gt;
        /// 
        ///&lt;p&gt;You can login to system by using your new password.&lt;br/&gt;
        /// 
        ///If you need any asistance, please don’t hesitate to contact us.&lt;/p&gt;.
        /// </summary>
        public static string ChangePassBody {
            get {
                return ResourceManager.GetString("ChangePassBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGED PASSWORD / ALFURSAN’s Client Login System..
        /// </summary>
        public static string ChangePassSubject {
            get {
                return ResourceManager.GetString("ChangePassSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Sayın &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///&lt;p&gt;Alfursan dosya takip sistemine yeni bir dosya eklendi. Dosyayı ekte bulabilirsiniz.&lt;/p&gt;&lt;p&gt;Ayrıca Alfursan dosya takip sistemine giriş yaparak aşağıdaki linkten erişebilirsiniz.&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;&lt;SiteRoot&gt;/Archive/Files&quot;&gt;&lt;SiteRoot&gt;/Archive/Files&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string FileUploadedBody {
            get {
                return ResourceManager.GetString("FileUploadedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfursan File Management - File Uploaded.
        /// </summary>
        public static string FileUploadedSubject {
            get {
                return ResourceManager.GetString("FileUploadedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Dear &lt;Name&gt; &lt;Surname&gt; ,&lt;/h4&gt;
        ///
        ///&lt;p&gt;Please click the link below to change your password. &lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;&lt;SiteRoot&gt;/Account/ResetPassword/&lt;ConfirmKey&gt;&quot;&gt;Change password&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If you need any other assistance please don’t hesitate to contact us.&lt;/p&gt;.
        /// </summary>
        public static string ForgotPasswordBody {
            get {
                return ResourceManager.GetString("ForgotPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Alfursan.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Dear  &lt;Name&gt; &lt;Surname&gt; ,&lt;/h4&gt;
        ///&lt;p&gt;Please view your files attached.&lt;/p&gt;.
        /// </summary>
        public static string NewFileUploadedBody {
            get {
                return ResourceManager.GetString("NewFileUploadedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALFURSAN- ACCOUNT FILE.
        /// </summary>
        public static string NewFileUploadedSubjectAccountDoc {
            get {
                return ResourceManager.GetString("NewFileUploadedSubjectAccountDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALFURSAN-VARIOUS FILES.
        /// </summary>
        public static string NewFileUploadedSubjectOther {
            get {
                return ResourceManager.GetString("NewFileUploadedSubjectOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALFURSAN- SHIPMENT DOCUMENTS .
        /// </summary>
        public static string NewFileUploadedSubjectShipmentDoc {
            get {
                return ResourceManager.GetString("NewFileUploadedSubjectShipmentDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Best Regards,&lt;/p&gt;
        ///&lt;p&gt;ALFURSAN Team &lt;br/&gt;
        ///Tel : 0090 212 246 44 30 &lt;br/&gt;
        ///E-mail : ccdep@alfursan.com.tr
        ///&lt;/p&gt;.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Dear &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///
        ///&lt;p&gt;ALFURSAN has been created username and password for you.&lt;/p&gt;
        ///&lt;p&gt;Please note your user name and password to use on Alfursan&apos;s Client Login system.&lt;/p&gt;
        ///
        ///&lt;p&gt;By this system you can reach your documents wherever you are. &lt;/p&gt;
        ///&lt;p&gt;( Invoice, Packing List, Eur1, AWB, your account statements and various files) &lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;
        ///Your user name : &lt;Email&gt;&lt;br/&gt;
        ///Your password: &lt;Password&gt;&lt;br/&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;Please click this link to login to the system  &lt;a href=&quot;http://pane [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeAdminBody {
            get {
                return ResourceManager.GetString("WelcomeAdminBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Dear &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///
        ///&lt;p&gt;ALFURSAN has been created username and password for you.&lt;/p&gt;
        ///&lt;p&gt;Please note your user name and password to use on Alfursan&apos;s Client Login system.&lt;/p&gt;
        ///
        ///&lt;p&gt;By this system you can reach your documents wherever you are. &lt;/p&gt;
        ///&lt;p&gt;( Invoice, Packing List, Eur1, AWB, your account statements and various files) &lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;
        ///Your user name : &lt;Email&gt;&lt;br/&gt;
        ///Your password: &lt;Password&gt;&lt;br/&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;Please click this link to login to the system  &lt;a href=&quot;http://pane [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeCustomerBody {
            get {
                return ResourceManager.GetString("WelcomeCustomerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Dear &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///
        ///&lt;p&gt;ALFURSAN has been created username and password for you.&lt;/p&gt;
        ///&lt;p&gt;Please note your user name and password to use on Alfursan&apos;s Client Login system.&lt;/p&gt;
        ///
        ///&lt;p&gt;By this system you can reach your documents wherever you are. &lt;/p&gt;
        ///&lt;p&gt;( Invoice, Packing List, Eur1, AWB, your account statements and various files) &lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;
        ///Your user name : &lt;Email&gt;&lt;br/&gt;
        ///Your password: &lt;Password&gt;&lt;br/&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;Please click this link to login to the system  &lt;a href=&quot;http://pane [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeCustomOfficerBody {
            get {
                return ResourceManager.GetString("WelcomeCustomOfficerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Alfursan File Managament !.
        /// </summary>
        public static string WelcomeSubject {
            get {
                return ResourceManager.GetString("WelcomeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Dear &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///
        ///&lt;p&gt;ALFURSAN has been created username and password for you.&lt;/p&gt;
        ///&lt;p&gt;Please note your user name and password to use on Alfursan&apos;s Client Login system.&lt;/p&gt;
        ///
        ///&lt;p&gt;By this system you can reach your documents wherever you are. &lt;/p&gt;
        ///&lt;p&gt;( Invoice, Packing List, Eur1, AWB, your account statements and various files) &lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;
        ///Your user name : &lt;Email&gt;&lt;br/&gt;
        ///Your password: &lt;Password&gt;&lt;br/&gt;
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;Please click this link to login to the system  &lt;a href=&quot;http://pane [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeUserBody {
            get {
                return ResourceManager.GetString("WelcomeUserBody", resourceCulture);
            }
        }
    }
}
