//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfursan.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alfursan.Web.App_GlobalResources.MailMessage", typeof(MailMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Sayın &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///&lt;p&gt;Aşağıdaki linke tıklayarak yeni şifrenizi belirleyebilirsiniz&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;a href=&quot;&lt;SiteRoot&gt;/Account/ResetPassword/&lt;ConfirmKey&gt;&quot;&gt;Şifremi değiştir.&lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string ForgotPasswordBody {
            get {
                return ResourceManager.GetString("ForgotPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Alfursan.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Sayın &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///&lt;p&gt;Alfursan dosya takip sistemine yeni bir dosya eklendi. Dosyayı ekte bulabilirsiniz.&lt;/p&gt;&lt;p&gt;Ayrıca Alfursan dosya takip sistemine giriş yaparak aşağıdaki linkten erişebilirsiniz.&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;&lt;SiteRoot&gt;/Archive/Files&quot;&gt;&lt;SiteRoot&gt;/Archive/Files&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string NewFileUploadedBody {
            get {
                return ResourceManager.GetString("NewFileUploadedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfursan File Management - New File Uploaded.
        /// </summary>
        public static string NewFileUploadedSubject {
            get {
                return ResourceManager.GetString("NewFileUploadedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Sayın &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///&lt;p&gt;Alfursan dosya takip sistemine hoşgeldiniz. Sisteme giriş bilgileriniz aşağıdaki gibidir. Bu bilgiler ile sistemimizde işlemlerinize ait dosyalara erişebilir talepleriniz için bizimle irtibata geçebilirsiniz.&lt;/p&gt;
        ///&lt;p&gt;
        ///Kullanıcı adı : &lt;Username&gt; (Email bilginiz ile de login olabilirsiniz (&lt;Email&gt;))
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Şifre : &lt;Password&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string WelcomeAdminBody {
            get {
                return ResourceManager.GetString("WelcomeAdminBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Sayın &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///&lt;p&gt;Alfursan dosya takip sistemine hoşgeldiniz. Sisteme giriş bilgileriniz aşağıdaki gibidir. Bu bilgiler ile sistemimizde işlemlerinize ait dosyalara erişebilir talepleriniz için bizimle irtibata geçebilirsiniz.&lt;/p&gt;
        ///&lt;p&gt;
        ///Kullanıcı adı : &lt;Username&gt; (Email bilginiz ile de login olabilirsiniz (&lt;Email&gt;))
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Şifre : &lt;Password&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string WelcomeCustomerBody {
            get {
                return ResourceManager.GetString("WelcomeCustomerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Sayın &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///&lt;p&gt;Alfursan dosya takip sistemine hoşgeldiniz. Sisteme giriş bilgileriniz aşağıdaki gibidir. Bu bilgiler ile sistemimizde işlemlerinize ait dosyalara erişebilir talepleriniz için bizimle irtibata geçebilirsiniz.&lt;/p&gt;
        ///&lt;p&gt;
        ///Kullanıcı adı : &lt;Username&gt; (Email bilginiz ile de login olabilirsiniz (&lt;Email&gt;))
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Şifre : &lt;Password&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string WelcomeCustomOfficerBody {
            get {
                return ResourceManager.GetString("WelcomeCustomOfficerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Alfursan File Managament !.
        /// </summary>
        public static string WelcomeSubject {
            get {
                return ResourceManager.GetString("WelcomeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Sayın &lt;Name&gt; &lt;Surname&gt; ;&lt;/h4&gt;
        ///&lt;p&gt;Alfursan dosya takip sistemine hoşgeldiniz. Sisteme giriş bilgileriniz aşağıdaki gibidir. Bu bilgiler ile sistemimizde işlemlerinize ait dosyalara erişebilir talepleriniz için bizimle irtibata geçebilirsiniz.&lt;/p&gt;
        ///&lt;p&gt;
        ///Kullanıcı adı : &lt;Username&gt; (Email bilginiz ile de login olabilirsiniz (&lt;Email&gt;))
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Şifre : &lt;Password&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string WelcomeUserBody {
            get {
                return ResourceManager.GetString("WelcomeUserBody", resourceCulture);
            }
        }
    }
}
